# -*- coding: utf-8 -*-
"""pytorch_nn_module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18pTRxILxqHI5SvZAEn3_Oi6nyZZboJtI

Single Neuron:
"""

import torch
import torch.nn as nn

# must inherit nn.Module as it is the base class which has all the implementation
class Model(nn.Module):

  # must call parents constructor
  def __init__(self,num_features):
    super().__init__()

    # define forward
    self.linear = nn.Linear(num_features,1) # single neuron
    self.sigmoid = nn.Sigmoid() # activation function

  def forward(self,features):

    # perform forward
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

# define features
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call forward
# outputs =model.forward(features) # non standard method
outputs=model(features) # standard method, automatically calls forward method(done by __call__ magic method)
print(outputs)

# inspect parameters
model.linear.weight
model.linear.bias

"""2 Layer Network:"""

import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    # define network
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):

    # perform forward
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

features = torch.rand(10,5) # define features
model = Model(features.shape[1]) # create model
outputs=model(features) # get outputs
print(outputs)

# inspect parameters
model.linear1.weight
model.linear1.bias
model.linear2.weight
model.linear2.bias

"""Using Sequential:"""

# use sequential to create network
# sequential automatically performs forword opertions when called

import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    # define network
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    # call forword
    out = self.network(features)
    return out

features = torch.rand(10,5) # define features
model = Model(features.shape[1]) # create model
outputs=model(features) # get outputs
print(outputs)

"""Torch Info:"""

# torchinfo helps inspect nn.Module
!pip install torchinfo

from torchinfo import summary
summary(model,input_size=(10,5))

