# -*- coding: utf-8 -*-
"""pytorch_training_with_nn_module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hf5Q0JLc1IrvlbdrSv0QDasOnipFayNE
"""

import pandas as pd
import torch
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

# import data and inspect
data = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
print(data.shape)
data.head()

# remove non-informative features
data.drop(columns=['id', 'Unnamed: 32'], inplace=True)

# train test split
x_train,x_test,y_train,y_test = train_test_split(data.iloc[:,1:],data.iloc[:,0],test_size=0.2)

# z-score standardization
scalar = StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test = scalar.transform(x_test)

# label encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

# coverting to tensors
x_train_tensor = torch.from_numpy(x_train.astype(np.float32))
x_test_tensor = torch.from_numpy(x_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))
print(x_train_tensor.shape)
print(y_train_tensor.shape)
print(x_test_tensor.shape)
print(y_test_tensor.shape)

import torch.nn as nn

# hyperparameters
learning_rate = 0.1
epochs = 25

# model class
class SimpleNN(nn.Module):

  def __init__ (self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.activation = nn.Sigmoid()
    self.lossFunction = nn.BCELoss()

  def forward(self,features):
    out = self.linear(features)
    out = self.activation(out)
    return out

  def loss_function(self,y_pred,y_train_tensor):
    loss = self.lossFunction(y_pred, y_train_tensor.view(-1,1))
    return loss

# create model
model = SimpleNN(x_train_tensor.shape[1])

#define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

# training
for epoch in range(epochs):
  y_pred = model(x_train_tensor) # get prediction
  loss = model.loss_function(y_pred, y_train_tensor) # calculate loss
  optimizer.zero_grad()   # clear old gradients
  loss.backward()         # compute new gradients
  optimizer.step()        # update weights
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

# model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')