# -*- coding: utf-8 -*-
"""PyTorch_autograd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CIKZeh9S4JeeEWqg6sMCsF_Jv9_leB0d

> Example 1
"""

# write a function to calculate diff of x**2
def dy_dx(x):
  return 2*x

res = dy_dx(3)
print(res)

import torch
x= torch.tensor(3.0, requires_grad=True)
# requires_grad=True tell pytorch track every operation involving this tensor so I can compute gradients later
# PyTorch marks x as a leaf tensor
# it starts a computation graph from here

y=x**2
# records this operation
# builds a node in the computation graph
# still, no gradients are calculated yet

y.backward()
# compute the gradient of y with respect to all tensors that have requires_grad=True
# Start from y
# Move backward through the graph
# Apply the chain rule
# Accumulate gradients into .grad

print(x.grad)

"""> Example 2"""

import math

# write a function to calculate diff of z
# where z= sin(y),y=x**2
def dz_dx(x):
  return 2*x*math.cos(x**2)
dz_dx(4)

x= torch.tensor(4.0,requires_grad=True)
y=x**2
z=torch.sin(y)
z.backward()
print(x)
print(y)
print(z)
print(x.grad)


# manual calculation

import torch

x= torch.tensor(6.7)
y=torch.tensor(0.0)

w= torch.tensor(1.0)
b= torch.tensor(0.0)

def binary_cross_entropy_loss(prediction, target):
  epsilon = 1e-8
  prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
  return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

# forword pass
z = w * x + b
y_pred = torch.sigmoid(z)
loss = binary_cross_entropy_loss(y_pred, y)
print(loss)

dloss_dypred = (y_pred - y)/(y_pred * (1 - y_pred))
dypred_dz = y_pred * (1 - y_pred)
dz_dw = x
dz_db = 1
dL_dw = dloss_dypred * dypred_dz * dz_dw
dL_db = dloss_dypred * dypred_dz * dz_db
print(f"Manual gradient of loss w.r.t weight (dw): ", dL_dw)
print(f"Manual gradient of loss w.r.t bias (dw): ", dL_db)


# using autogard

x = torch.tensor(6.7)
y = torch.tensor(0.0)
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)
z = w*x + b
y_pred = torch.sigmoid(z)
loss = binary_cross_entropy_loss(y_pred, y)
loss.backward()
print(w.grad)
print(b.grad)

"""> Disable gradient tracking:"""

# option 1 - requires_grad_(False)
# option 2 - detach()
# option 3 - torch.no_grad()
x.requires_grad_(False)
x.detach()
with torch.no_grad():
  y = x**2
  print(y)