# -*- coding: utf-8 -*-
"""PyTorch_tensors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ISMKK0wS9_iQnEC4-48T1A-gG6kwGn8v

> Import
"""

import torch
print(torch.__version__)

"""> CUDA"""

if torch.cuda.is_available():
    print("CUDA is available.")
    print(f"Number of CUDA devices: {torch.cuda.device_count()}")
    print(f"Number of CUDA devices: {torch.cuda.get_device_name()}")

else:
    print("CUDA is not available.")

"""> Tensor Creation Funtions:"""

a=torch.empty(2,3)
# returns a tensor filled with unitialized data
# does not fill any value, rather display what value is already present at that location

b=torch.zeros(2,3)
# returns a tensor filled with zeros

c=torch.ones(2,3)
# returns a tensor of filled with ones

d=torch.rand(2,3)
# returns a tensor of filled with random values
# they are random everytime we initialize
# but some times we want reproducability, to get same values always we use seed

e = torch.tensor([[1, 2, 3],[1,3,4]])
# creates a tensor with the given values

print(a)
print(b)
print(c)
print(d)
print(e)

print("using arange ->", torch.arange(0,10,2)) # (start,end,step)
# returns a tensor filled with given start and end values
# step helps skip values

print("using linspace ->", torch.linspace(0,10,5)) # (start,end,num_of_values)
# returns a scalar tensor with given start and end values
# size of tensor depends on num_of_values

print("using eye ->",torch.eye(5)) # (n)
# returns a identity tensor
# shape depends on n variable i.e n*n

print("using full ->",torch.full((2,3),4)) # ((shape),value)
# returns a tensoer with same value

"""> Seed:"""

torch.manual_seed(100)
a = torch.rand(2,3)
print(a)

torch.manual_seed(100)
b = torch.rand(2,3)
print(b)

# seed helps return the same values everytime with rand function
# rand  uses a sequence of values for the data and they are random everytime we initialise it
# we can generate same sequence using the same seed value

"""> Utility Functions:"""

a = torch.tensor([[1,2,3],[4,5,6]])

# type
print("type of tensor:", type(a))

# shape of tensor
print("shape of tensor:", a.shape)

# data type of tensor
print("data type of tensor:", a.dtype)

# device of tensor
print("device of tensor:", a.device)

# specifying dtype of tensor
torch.tensor([1.0,2.0],dtype=torch.int32)

""">Tensor Initialization Based on Existing Tensors:


"""

a = torch.tensor([[1,2,3],[4,5,6]])

b=torch.empty_like(a)
print(b)
# returns an uninitialized tensor with same shape as input

c=torch.zeros_like(a)
print(c)
# returns a tensor filled with zeros with same shape as input

d=torch.ones_like(a)
print(d)
# returns a tensor filled with ones with same shape as input

e=torch.rand_like(a,dtype=torch.float32)
print(e)
# returns a tensor filled with random values with same shape as input
# rand only return float so we must convert the input tensor to floats by specifying dtype

"""> DataType Conversions:"""

a= torch.tensor([[1,2,3],[4,5,6]])
b=a.to(torch.float32)
print(a.dtype)
print(b.dtype)

# it converts dtype of tensors

"""> Element-wise Arithmetic Tensor Operations:"""

x= torch.rand(2,3)
print(x)

print("addition: ", x+2)
print("subtraction: ", x-2)
print("multiplication: ", x*2)
print("division: ", x/2)
print("int division: ", x//3)
print("power: ", x**2)
print("modulus: ", x%2)

# scalar operations apply for each and every individual elements of the tensor

k = torch.randint(size=(2,3),low=0,high=10,dtype= torch.float32)
print(k)

print("log:",torch.log(k))
print("sigmoid",torch.sigmoid(k))
print("tanh",torch.tanh(k))
print("relu",torch.relu(k))
print("softmax",torch.softmax(k,dim=1))
print("sqrt:",torch.sqrt(k))
print("exp:",torch.exp(k))

"""> Element-wise Arithmetic Tensor Operations Between Matrices:"""

a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

print("addition: ",a+b)
print("subtraction: ",a-b)
print("multiplication: ",a*b)
print("division: ",a/b)
print("modular: ",a%b)
print("power: ",a**b)


# Both tensors have the same shape
# PyTorch performs element-wise operations
# Each element in a interacts with the element in the same position in b

# note:
# same shape is not strictly enforced
# two dimensions are compatible if: they are equal or One of them is 1

"""> Element-wise Tensor Transformations & Clipping"""

a= torch.tensor([1,-3,5,-2])
print(a)

# abs()
b = torch.abs(a)
# converts all values to their absolute value

# neg()
c = torch.neg(a)
# changes the sign of each element

# round()
d = torch.round(a)
# rounds each element to the nearest integer

# ceil()
e = torch.ceil(a)
# rounds each element UP to the nearest integer

# floor()
f = torch.floor(a)
# rounds each element DOWN to the nearest integer

# clamp()
g = torch.clamp(a,min=2,max=3)
# restricts values to a given range [min, max]
# values < min become min, values > max become max

print("abs:",b)
print("neg:",c)
print("round:",d)
print("ceil:",e)
print("floor:",f)
print("clamp:",g)

"""> Reduction & Statistical Operations on Tensors"""

a= torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

# sum
print("sum of all the elements of the tensor:",torch.sum(a))
# sum along columns
print("sum along the colums:",torch.sum(a,dim=0))
# sum along rows
print("sum along the rows:",torch.sum(a,dim=1))
print(" ********************************************* ")

# mean
print("mean of all the elements of the tensor:",torch.mean(a))
# mean along the columns
print("mean along the colums:",torch.mean(a,dim=0))
# mean along the rows
print("mean along the rows:",torch.mean(a,dim=1))
print(" ********************************************* ")


# median
print("median of all the elements of the tensor:",torch.median(a))
# median along columns
print("median along the colums:",torch.median(a,dim=0))
# median along rows
print("median along the rows:",torch.median(a,dim=1))
print(" ********************************************* ")


# max
print("max of all the elements of the tensor:",torch.max(a))
# max along columns
print("max along the colums:",torch.max(a,dim=0))
# max along rows
print("max along the rows:",torch.max(a,dim=1))
print(" ********************************************* ")


# min
print("min of all the elements of the tensor:",torch.min(a))
# min along columns
print("min along the colums:",torch.min(a,dim=0))
# min along rows
print("min along the rows:",torch.min(a,dim=1))
print(" ********************************************* ")


# product
print("product of all the elements of the tensor:",torch.prod(a))
# product
print("product along the colums:",torch.prod(a,dim=0))
# product
print("product along the rows:",torch.prod(a,dim=1))
print(" ********************************************* ")


# standard deviation
print("standard deviation of all the elements of the tensor:",torch.std(a))
# standard deviation along columns
print("standard deviation along the colums:",torch.std(a,dim=0))
# standard deviation along rows
print("standard deviation along the rows:",torch.std(a,dim=1))
print(" ********************************************* ")


# variance
print("variance of all the elements of the tensor:",torch.var(a))
# variance along columns
print("variance along the colums:",torch.var(a,dim=0))
# variance along rows
print("variance along the rows:",torch.var(a,dim=1))
print(" ********************************************* ")


# argmax
print("argmax of all the elements of the tensor:",torch.argmax(a))
# argmax along the columns
print("argmax along the colums:",torch.argmax(a,dim=0))
# argmax along the rows
print("argmax along the rows:",torch.argmax(a,dim=1))
print(" ********************************************* ")


# argmin
print("argmin of all the elements of the tensor:",torch.argmin(a))
# argmax along the columns
print("argmin along the colums:",torch.argmin(a,dim=0))
# argmax along the rows
print("argmin along the rows:",torch.argmin(a,dim=1))

"""> Linear Operations of Tensors:"""

# matmul():
a = torch.randint(size=(2,3),low=0,high=10)
b = torch.randint(size=(3,2),low=0,high=10)
c=torch.matmul(a,b)
print("matrix multiplication of a and b: ",c)
d = torch.mm(a,b)
print("matrix multiplication of a and b: ",d)


# dot():
a= torch.tensor([1,2])
b= torch.tensor([3,4])
c = torch.dot(a,b)
print("dot product a1 and b1 ",c)


# transpose():
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
b= torch.transpose(a,0,1)
print("transpose of a: ",b)

# det():
a= torch.randint(size=(2,2),low=0,high=10,dtype=torch.float32)
print("determinant of a: ",torch.det(a))

# inverse():
a= torch.randint(size=(2,2),low=0,high=10,dtype=torch.float32)
print("inverse of a: ",torch.inverse(a))

"""> Element Wise Comparisons:"""

i =  torch.randint(size=(2,3),low=0,high=10)
j =  torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

print("i greater than j:",i>j)
print("i less than j:",i<j)
print("i equal to j:",i==j)
print("i not equal to j:",i!=j)
print("i greater than equal to j:",i>=j)
print("i less than equal to j:",i<=j)

"""> In-Place Operations:"""

m= torch.rand(2,3)
n= torch.rand(2,3)
print(m)
print(n)

m+n # the result is stored in completely new tensor (which is not desirable ,we want changes to be in place)

# functionName_() helps performing operations in place
m.add_(n)
m.relu_()
print(m)

"""> Cloning Tensor:"""

a = torch.rand(2,3)
b = a # but the problem in this approach is that if something is changed in the orginal a then it will also effect on b(just pointing a reference)
print(a)
print(b)

a[0][0]=0
print(a)
print(b)

print(id(a))
print(id(b))

a = torch.rand(2,3)
b= a.clone()
# creates a new tensor completely seperated and independent

"""> Reshaping Tensors:"""

# reshape() and flatten():

a= torch.ones(4,4)
a.reshape(2,2,2,2)
# it changes the view of the tensor without changing data
# rule: product of old shape == product of new shape
# 4 × 4 = 2 × 2 × 2 × 2 = 16

a.flatten()
# it collapses all dimensions into one dimension
# useful before feeding data into fully connected (linear) layers


# permute():

b= torch.rand(2,3,4)
b.permute(2,0,1).shape
# it reorders dimensions without changing data
# new order: (2, 0, 1)
# old: (2, 3, 4)
# new: (4, 2, 3)


# unsqueeze() and squeeze():

c=torch.rand(226,226,3)
c.unsqueeze(1).shape
# it adds a dimension of size 1 at the given index
# lets say a models is image classification
# now generally models expect input in the form of a batch, unsqueeze helps achieve this

d= torch.rand(1,20)
d.squeeze(0).shape
# it removes a dimension only if its size is 1

"""> Tensor Operations on GPU:"""

# storing the GPU device on variable
torch.cuda.is_available()
device = torch.device('cuda')
print(device)


# creating new tensor on the GPU
torch.rand(2,3,device=device)

# moving existing tensors to gpu
a= torch.rand(2,3) # created in cpu
a_on_gpu= a.to(device) # moving to GPU
print(a_on_gpu)

import time

def benchmark_matmul(device, size=(1000, 1000)):
    # Create two random matrices
    a = torch.rand(size, device=device)
    b = torch.rand(size, device=device)

    # Warm-up run (especially important for GPU)
    for _ in range(10):
        torch.matmul(a, b)

    # Synchronize GPU before timing, if on GPU
    if device.type == 'cuda':
        torch.cuda.synchronize()

    start_time = time.time()
    for _ in range(100):  # Repeat multiple times for more accurate measurement
        c = torch.matmul(a, b)

    # Synchronize GPU after timing, if on GPU
    if device.type == 'cuda':
        torch.cuda.synchronize()

    end_time = time.time()
    return end_time - start_time

# Define device types
cpu_device = torch.device('cpu')
gpu_device = torch.device('cuda') if torch.cuda.is_available() else None

matrix_size = (2000, 2000) # You can adjust this size

# Benchmark on CPU
print(f"Benchmarking matrix multiplication ({matrix_size[0]}x{matrix_size[1]}) on CPU...")
cpu_time = benchmark_matmul(cpu_device, size=matrix_size)
print(f"CPU time: {cpu_time:.4f} seconds")

# Benchmark on GPU (if available)
if gpu_device:
    print(f"\nBenchmarking matrix multiplication ({matrix_size[0]}x{matrix_size[1]}) on GPU...")
    gpu_time = benchmark_matmul(gpu_device, size=matrix_size)
    print(f"GPU time: {gpu_time:.4f} seconds")

    # Calculate and print the speedup ratio
    if gpu_time > 0:
        speedup_ratio = cpu_time / gpu_time
        print(f"\nSpeedup (CPU / GPU): {speedup_ratio:.2f}x")
else:
    print("\nCUDA is not available, skipping GPU benchmark.")

"""> Numpy and PyTorch Conversions:"""

import numpy as np
import torch

a= torch.tensor([1,2,3])
b= a.numpy()

print("type of a: ",type(a))
print("type of b: ",type(b))