# -*- coding: utf-8 -*-
"""pytorch_training_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vlbNGPERnQp2N0V1HLpjNYRLC-L6DwVn
"""

import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


# import data and inspect
data = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
print(data.shape)
data.head()


# remove non-informative features
data.drop(columns=['id', 'Unnamed: 32'], inplace=True)

# train test split
x_train,x_test,y_train,y_test = train_test_split(data.iloc[:,1:],data.iloc[:,0],test_size=0.2)

# z-score standardization
scalar = StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test = scalar.transform(x_test)

# label encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

# coverting to tensors
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)
print(x_train_tensor.shape)
print(y_train_tensor.shape)
print(x_test_tensor.shape)
print(y_test_tensor.shape)


# hyperparameters
learning_rate = 0.1
epochs = 25

# model class
class SimpleNN():

  def __init__ (self,x_train_tensor):
    self.weights = torch.rand(x_train_tensor.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,x_train_tensor):
    z = torch.matmul(x_train_tensor,self.weights)+self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilon =1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
    loss = -(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred)).mean()
    return loss


# create model
model = SimpleNN(x_train_tensor)

# training
for epoch in range(epochs):
  y_pred = model.forward(x_train_tensor)
  loss = model.loss_function(y_pred, y_train_tensor)
  loss.backward()
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  model.weights.grad.zero_()
  model.bias.grad.zero_()
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

# model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')